// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DataService.proto

package com.epam.grpc.proto;

public interface DataResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.epam.grpc.proto.DataResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
