// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DataService.proto

package com.epam.grpc.proto;

public final class DataServiceOuterClass {
  private DataServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_epam_grpc_proto_DataRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_epam_grpc_proto_DataRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_epam_grpc_proto_DataResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_epam_grpc_proto_DataResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021DataService.proto\022\023com.epam.grpc.proto" +
      "\"\036\n\013DataRequest\022\017\n\007message\030\001 \001(\t\"\037\n\014Data" +
      "Response\022\017\n\007message\030\001 \001(\t2_\n\013DataService" +
      "\022P\n\007getData\022 .com.epam.grpc.proto.DataRe" +
      "quest\032!.com.epam.grpc.proto.DataResponse" +
      "\"\000B\027\n\023com.epam.grpc.protoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_epam_grpc_proto_DataRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_epam_grpc_proto_DataRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_epam_grpc_proto_DataRequest_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_com_epam_grpc_proto_DataResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_epam_grpc_proto_DataResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_epam_grpc_proto_DataResponse_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
