server:
  port: 8081
spring:
  application:
    name: grpc-client

grpc:
  client:
    grpc-server:
      address: 'static://127.0.0.1:8080'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext